version: '3'

services:
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_db
